### ISSUE TITLE
"TypeError: Cannot read property 'setMaxListeners' of undefined"

### ISSUE THREAD

**Issue by nicgord** [nabbl/node-red-contrib-google-home-notify#1] opened 2017-09-07 05:39 UTC
I love the idea for this and am keen to get working...

I am receiving the following error in the debug window....

Any ideas?

**Comment by nicgord** [comment] 2017-09-07 11:05
Just an update, I selected a language that was not default and error gone.

Thanks for this add on... it has changed my life!

**Comment by torinnguyen** [comment] 2017-10-17 05:21
duplicate of this issue #2

**Closed** 2017-11-13 19:21 UTC
